### ISSUE TITLE
Remix + Ganache - Cannot call one contract from another

### ISSUE THREAD

**Issue by anandamarsh** [trufflesuite/ganache-core#242] opened 2018-12-04 00:33 UTC
I have an innocent looking contracts that work painlessly in Remix. Test contract can easily call Another if I use JavaScript VM in Remix. 

I also have ganache-cli running on port 7454. If I connect Remix to ganache-cli, each of these contracts work well individually. But I cant call Another from Test. Remix console says `transact to Test.send errored: VM Exception while processing transaction: revert ` 

My contracts look like:

```
    pragma solidity 0.4.25;
    
    contract Another {
        uint public balance;
        function sendToAnother() public {
            balance += 10;
        }
    }
    
    contract Test {
        function send(address another) public {
            Another(another).sendToAnother();
        }
    }
```

## Expected Behavior
The contract works as is in JavaScript VM and Ropsten (with Metamask) as expected. Also, individual contacts work with ganache-cli. Just calling one contract from another doesnt seem to work. 

## Current Behavior
`transact to Test.send errored: VM Exception while processing transaction: revert `

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. Put he given contract in Remix Editor
2. Run ganache-ui. It starts on port 7545
3. Run the SmartContract after setting the Environment to Web3 Provider
4. Deploy the Another Contract first
5. Deploy the Test Contract next
6. Call the method `send()` with address of Another contract

## Your Environment
* Version used ; ganache-ui 1.2.2, Solidity 0.5.0
![screen shot 2018-12-04 at 11 14 35 am](https://user-images.githubusercontent.com/10276735/49410350-58c2ba80-f7b8-11e8-88fa-fd81b5e6a2cc.png)
![screen shot 2018-12-04 at 11 14 25 am](https://user-images.githubusercontent.com/10276735/49410366-6710d680-f7b8-11e8-89d0-779dbf930000.png)

**Comment by anandamarsh** [comment] 2018-12-04 22:01
Thanks David. If this is happening with everyone (unable to call one contract from another), then it’s a serious impediment, and should be given a higher priority. If this is a version incompatibility type issue, we can perhaps leave it on a medium priority. 
For myself, I am currently manoeuvring by routing these inter-contract calls through my Dapp for development purposes.

**Comment by fbalwy** [comment] 2019-02-18 18:17
I am facing the same problem :(

**Comment by anandamarsh** [comment] 2019-02-18 20:35
Yeah I just turned away from Ganache. Used Roosten test network directly.

**Comment by davidmurdoch** [comment] 2019-02-18 20:40
@fbalwy, @anandamarsh this is caused by an out of gas error within the call to the nested contract (which bubbles up to the initial contract call and gets treated as a revert) and we are very close to releasing a beta with a fix for it. PR is here: https://github.com/trufflesuite/ganache-core/pull/292

**Comment by fbalwy** [comment] 2019-03-15 19:30
It's been 25 days since labeling this issue as  **_priority-high_**. Any news about releasing a beta with a fix for this issue?

**Comment by davidmurdoch** [comment] 2019-03-15 23:01
@fbalwy I'll finally be releasing the beta on Monday!

**Comment by nicholasjpaterno** [comment] 2019-03-28 17:27
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!

**Closed by nicholasjpaterno** 2019-03-28 17:27 UTC
Labels: priority-high
