### ISSUE TITLE
Look into Javascript-based testing option for `debug_traceTransaction`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/ganache-core#47] opened 2018-01-04 21:56 UTC
Via the `tracer` JSON-RPC option.

**Docs:** https://github.com/ethereum/go-ethereum/wiki/Management-APIs#javascript-based-tracing

**Comment by gnidan** [comment] 2018-01-05 00:03
**Possible pro argument:**

The trace steps without the use of this operating mode exist purely as data - while this is useful as being generic, using the Javascript interface means we get objects, with convenient methods for the appropriate data types in the trace step.

**Possible con argument:**

Javascript that executes has to be passed as string, and only gives serialized results back. This is a lot of overhead.

**Comment by gnidan** [comment] 2018-01-11 21:55
This actually sounds like a bad idea.

**Comment by Kevnz** [comment] 2018-03-25 22:54
By not having this, and closing the door on it means that ganache is not, nor will it ever be a full solution for local development. I appreciate that it can add overhead, but if the idea is for ganache to allow for personal development not supporting something does not help it achieve it's goal. If you aren't going to support features you should clearly label unsupported features on the front page.

**Comment by sabondano** [comment] 2018-11-27 22:06
@davidmurdoch the conversation above accurate and up to date? Custom tracers with `debug_traceTransaction` are not currently supported by ganache-core?

**Comment by sabondano** [comment] 2018-11-27 22:52
@davidmurdoch nvm. @gnidan confirmed on gitter that it's not currently supported. Thank you!

**Comment by LogvinovLeon** [comment] 2019-01-18 14:16
Confirming that this issue is still valid for me. I'm unable to request traces for big transactions because they're containing too much data. In Geth, I can pass a custom tracer and get just the data I need.

The problem is specifically with the stack values. Stack usually is pretty big and if we repeat it on every opcode struct log it's quadratic. What I'm doing is tracing the call stack, so I only need to access stack on call-like opcodes.

Here is my current solution:
https://github.com/0xProject/0x-monorepo/blob/development/packages/sol-tracing-utils/src/trace_info_subprovider.ts#L18
<img width="932" alt="screen shot 2019-01-18 at 3 15 58 pm" src="https://user-images.githubusercontent.com/6204356/51392001-ff2e0980-1b33-11e9-9bf8-5c449b2fba01.png">


Would be very nice to support that.

**Comment by davidmurdoch** [comment] 2019-01-18 15:11
Good points, @LogvinovLeon. I'll reopen this issue.

**Comment by benjamincburns** [comment] 2019-03-14 08:26
I'm afraid the security concerns behind this proposal are just too big to ignore. Rather than continuing to debate the merits of this specific proposal, let's move this conversation over to #381 where we can evaluate other proposals in the context of (hopefully) well-stated goals.

**Closed by benjamincburns** 2019-03-14 08:26 UTC
Labels: enhancement, priority-low
