### ISSUE TITLE
Husky throws an error if `ganache-core` is a dependency in a project

### ISSUE THREAD

**Issue by ylv-io** [trufflesuite/ganache-core#562] opened 2020-04-14 19:29 UTC
## Expected Behavior
Expect Husky not to throw an error on Git commands.

## Current Behavior
Git `commit` would cause an error.

```bash
not found: husky-run
Can't find Husky, skipping pre-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
On branch master
```

## Steps to Reproduce (for bugs)
1. git init
2. npm init
3. npm i -D ganache-core
4. git commit -m 'test'

## Context
You have to delete Git hooks to continue the development.

## Your Environment
* Version used: 2.10.2
* Operating System and version: MacOS Catalina 10.15.3 (19D76)

**Comment by alcuadrado** [comment] 2020-04-15 22:07
I'm seeing the exact same problem. The issue is that you are including husky in your shrinkwrap file.

**Comment by frangio** [comment] 2020-06-19 19:08
Are there any plans to fix this?

**Comment by davidmurdoch** [comment] 2020-06-20 00:56
Yes! I'll try to get it done next week.

**Comment by alcuadrado** [comment] 2020-06-25 13:02
I can confirm that `2.11.0-beta.0` fixes this

**Comment by alcuadrado** [comment] 2020-10-01 16:10
Hey @davidmurdoch, this happened once again, and `ganache-core@2.12.1` pulls its dev dependencies, including husky, once again.

**Comment by davidmurdoch** [comment] 2020-10-01 20:41
Thanks, @alcuadrado! It should already be fixed in the latest alpha release that I'm smoke testing now.

**Comment by alcuadrado** [comment] 2020-10-05 14:54
I just tried the alpha release, and it doesn't include husky, nor compiles any native dependency 🎉

When can we expect this to be released as non-alpha nor beta?

**Comment by davidmurdoch** [comment] 2020-10-05 17:47
Thanks for giving it a try @alcuadrado! What version of node did you install with?

And for release to beta, maybe today, and if that goes well, stable should be released by end of week, maybe even sooner.

**Comment by alcuadrado** [comment] 2020-10-05 17:53
Awesome news! 

I tried it with node v10.22.1 and npm v6.14.6

**Comment by davidmurdoch** [comment] 2020-10-06 21:02
Fixed (again) in https://github.com/trufflesuite/ganache-core/releases/tag/v2.13.0-beta.0 and https://github.com/trufflesuite/ganache-cli/releases/tag/v6.11.1-beta.1

**Closed by davidmurdoch** 2020-10-06 21:02 UTC
Labels: bug, priority-high
