### ISSUE TITLE
createAccount happens even if you have a database

### ISSUE THREAD

**Issue by mattkanwisher** [trufflesuite/ganache-core#22] opened 2017-10-23 16:57 UTC
## Expected Behavior
Reuse accounts when persisting the database to disk.

## Current Behavior
Even if you store to a database with the --db_path flag, when you reload the server it will create new accounts.
I would expect it would keep the same wallets from before, not create new accounts every time you run testrpc.

## Possible Solution
Save the accounts/private keys to a json file, and reload them on next start.

## Steps to Reproduce (for bugs)
node cli.js  --db testdata
kill it
node cli.js  --db testdata

I understand the cli is from testrpc package, but the actual code is in this package

## Context
Trying to have a semi reusable test blockchain, that can persist to disk and be reloaded. For testing out code.

## Your Environment
* Version used: Ganacha-core 1.1.4 and testRPC master GIT 29c5115609b909b32774bbaa820c8744db50a74e
* Environment name and version: Node 8.6.0
* Operating System and version: OSX
* Link to your project: http://loomx.io

**Comment by JanezStupar** [comment] 2018-01-15 13:05
Same here.

**Comment by seesemichaelj** [comment] 2019-01-11 06:54
Thanks for reporting this! I know it's been _a really long time_, and we're super sorry about that! I don't think this is an issue by design.

To be able to reuse the same accounts, you need to make sure you use the same mnemonic as the first time. You can specify the the mnemonic with `-m` or `--mnemonic`.  Or you can specify a seed which will generate the same mnemonic each time with `-s` or `--seed` when you first create the db as well as subsequent sessions.

You can also use a predefined mnemonic with `-d` or `--deterministic`.

Because of this and the age of this issue, I'm going to go ahead and close this.

**Closed by seesemichaelj** 2019-01-11 06:54 UTC
Labels: priority-medium
