### ISSUE TITLE
Incorrect trace steps generated for mainnet transaction 0x5d7ba47737fb9bd339a124c8ebce583071904f6d7ec6e99bb4d17dab32546e2f?

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/ganache-core#605] opened 2020-08-12 23:13 UTC
## Expected Behavior
Mainnet transaction `0x5d7ba47737fb9bd339a124c8ebce583071904f6d7ec6e99bb4d17dab32546e2f` has a status of `true`, i.e., it is successful.  As such, if I fork Ganache and get a trace for it, the trace should be consistent with that status.

## Current Behavior
Instead, the trace ends on a `REVERT` at depth 0.  There is no way that a trace ending on a `REVERT` at depth 0 can be successful -- either the `REVERT` succeeds, yielding an unsuccessful transaction, or the `REVERT` fails due to insufficient gas, in which case the transaction is also unsuccessful.

Since the transaction was mined as successful on mainnet, the best explanation here seems to be that Ganache is returning an incorrect trace for some reason?

## Steps to Reproduce (for bugs)
1. Start up Ganache, forking mainnet
2. Fetch the receipt for transaction 0x5d7ba47737fb9bd339a124c8ebce583071904f6d7ec6e99bb4d17dab32546e2f; observe that it contains logs and has `status: true`
3. Look up [this transaction on Etherscan](https://etherscan.io/tx/0x5d7ba47737fb9bd339a124c8ebce583071904f6d7ec6e99bb4d17dab32546e2f), again observe that it has `status: true` and contains logs, to confirm that this is true on mainnet and not a Ganache artifact
4. Get a trace for this transaction and observe that it ends, at depth 0, on a `REVERT`

## Your Environment
* Version used: Ganache CLI v6.10.1 (ganache-core: 2.11.2)
* Operating System and version: Release Linux Mint 20 Ulyana 64-bit

**Comment by seesemichaelj** [comment] 2020-08-24 22:28
Duplicate of #611

**Closed by seesemichaelj** 2020-08-24 22:28 UTC
Labels: bug, forking
