### ISSUE TITLE
estimateGas returns invalid value when tx has a gasRefund

### ISSUE THREAD

**Issue by perissology** [trufflesuite/ganache-core#26] opened 2017-10-29 17:00 UTC
When calling `eth_estimateGas`, the returned value is incorrect for the following cases:

1. transaction set a non-0 state variable to 0 thus resulting in a gas refund. The returned value is the transaction receipt gasUsed value, but in reality you need the tx receipt gasUsed + gasRefund to execute the tx, as gas is refunded at the end of the tx.

2. If there is a strange gas check in the contract function. ex:

```
contract FunkyGasPattern {
	string public field;

	function SetField(string value) {
	    // This check will screw gas estimation! Good, good!
   	    if (msg.gas < 100000) {
		    throw;
	    }
	    field = value;
        }
}
```

 

## Expected Behavior

estimateGas provides the correct gas to successfully execute a tx.
## Current Behavior

estimateGas does not always provide the correct gas to successfully execute a tx.
## Possible Solution

A simple fix for case 1 is in `statemanager.processGasEstimate` return the following:
``` return callback(null, to.hex(results.gasUsed.iadd(results.vm.gasRefund))) ```

A more thorough solution would be to implement a binary search for estimate gas as geth & metamask do. Possibly just updating the `web3-provider-engine` version and using their estimateGas method would work, assuming it doesn't break anything else

https://github.com/ethereum/go-ethereum/pull/3587
https://github.com/MetaMask/provider-engine/pull/119/files

I'd be happy to implement either, but thought I'd post for feedback to see what would be preferred.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by seesemichaelj** [comment] 2018-03-08 04:09
I was having this issue in https://github.com/trufflesuite/ganache-cli/issues/412 and favored for the option 1 for implementation. I believed that the gasRefund should actually be reported by `ethereumjs-vm` rather than accessing it directly and opened https://github.com/ethereumjs/ethereumjs-vm/issues/283 and https://github.com/ethereumjs/ethereumjs-vm/pull/284 to add the refund to the transaction results.

I'm going to go ahead and submit my PR for option 1, but I think we should discuss more and figure out the correct solution.

**Comment by seesemichaelj** [comment] 2018-06-18 19:44
I'm going to add this here: https://github.com/trufflesuite/truffle/issues/1012 is being caused by this issue

**Comment by benjamincburns** [comment] 2018-08-13 18:31
David's current effort will close this issue when it's completed.

**Comment by davidmurdoch** [comment] 2018-08-15 22:03
Fixed in https://github.com/trufflesuite/ganache-core/commit/81e8f59d74bcb38773498c34c78fb7d35a22af7f

**Closed by davidmurdoch** 2018-08-15 22:03 UTC

**Comment by perissology** [comment] 2018-08-15 22:17
did anyone test this using a proxy contract? From what I remember when I was experimenting w/ this adding the gasRefund will not work in all cases. 

https://github.com/trufflesuite/ganache-core/issues/26#issuecomment-371431421

**Comment by davidmurdoch** [comment] 2018-08-16 19:56
@perissology, once issue #147 has been implemented we should have much better gas estimation in an efficient manner. I'm planning on working on this soon, but if you'd still like to implement it let me know. I've got a single failing gas estimation test in a separate branch if you'd want to start from there (you don't have to use this specific test or branch): https://github.com/trufflesuite/ganache-core/tree/step-tracker
