### ISSUE TITLE
Execution Timeout on Exponentiation with Dynamically Generated Base

### ISSUE THREAD

**Issue by hysz** [trufflesuite/ganache-core#430] opened 2019-05-23 17:36 UTC
Smart contract execution will timeout in scenarios where the base is dynamically generated. 

## Steps to Reproduce
Call the solidity function below with `n >= 1` and execution will timeout.
```
function bad(uint256 n) public pure returns (uint256) {
    uint256 m = 2**n;
    return m**n;
}
```

Call a similar function with the same input and execution _will not_ timeout:
```
function good(uint256 n) public pure returns (uint256) {
    uint256 m = 2**(n*n);
    return m;
}
```

## Your Environment

* Version used: Ganache Core 2.5.3
* Operating System and version: Mac OS 10.13.6
* Solidity version 0.5.8
* Optimizer can be either on or off
* Also can be reproduced in Javascript VM on remix.ethereum.org (app version 0.7.7)

**Comment by haltman-at** [comment] 2021-03-10 18:41
Given that this happens under Remix as well, it sounds like the issue is probably with the EthereumJS VM.  Would you mind submitting this issue to them? https://github.com/ethereumjs/ethereumjs-monorepo  Thank you!

**Comment by davidmurdoch** [comment] 2021-04-28 18:45
Closing for issue maintenance.

**Closed by davidmurdoch** 2021-04-28 18:45 UTC
Labels: bug, needs validation
