### ISSUE TITLE
receipt.gasUsed incorrect for same-block transactions.

### ISSUE THREAD

**Issue by beether** [trufflesuite/ganache-core#90] opened 2018-03-18 09:13 UTC
I haven't dug deeply into this, but if you submit multiple transactions on the same block, all transaction receipts will have this bug:  

1. `receipt.gasUsed`'s value will be the `cumulativeGasUsed` up until that transaction.
2. `receipt.cumulativeGasUsed` will be the `cumulativeGasUsed` for the entire block.

**Comment by nicholasjpaterno** [comment] 2018-10-17 16:59
I believe this is a duplicate of https://github.com/trufflesuite/ganache-cli/issues/445.  We've just made some changes that should fix this issue.  I'm going to close this for now.  If you think this is an error please feel free to respond back here and reopen this issue.  Thanks for reporting!

**Closed by nicholasjpaterno** 2018-10-17 16:59 UTC
Labels: correctness/consistency, needs validation, priority-high
