### ISSUE TITLE
Ganache shouldn't assume that every transaction with data is a contract call

### ISSUE THREAD

**Issue by bordalix** [trufflesuite/ganache-core#117] opened 2018-05-25 13:42 UTC
I think I found a bug, where Ganache assumes that every transaction with data must be a contract call, which forbids to send transactions with data to non-contract accounts.

Imagine I'm sending a transaction from address1 to address2 (both non-contract accounts) with some data on it.

The function [_transactionIsContractCall](https://github.com/trufflesuite/ganache-core/blob/c7a2f69cad6bd8d73a67c300e8eb9816b44d694c/lib/statemanager.js#L849) will return true since the transaction has some data, defining it as a contract call (which is wrong).

On [line 832](https://github.com/trufflesuite/ganache-core/blob/c7a2f69cad6bd8d73a67c300e8eb9816b44d694c/lib/statemanager.js#L832) of the same file, since the **_transactionIsContractCall** function returned true, Ganache will now expects for the transaction to have some code, which it don't (since I'm not calling any function, I'm just sending some Ether to address2), so a new **TXRejectedError** will be raised, rejecting the transaction.

Shouldn't transactions to non-contract accounts be able to send some data?

Here is what the [Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf) states on point 4.2:
> 
> There are two types of transactions: those which result in message calls and those which result in the creation of new accounts with associated code (known informally as ‘contract creation’). Both types specify a number of common fields:
> ...
> Additionally, a contract creation transaction contains:
> **init**: An unlimited size byte array specifying the EVM-code for the account initialisation procedure, forma formally Ti.
> ...
> In contrast, a message call transaction contains:
> **data**: An unlimited size byte array specifying the input data of the message call, formally Td.

Is my understanding that the Ethereum protocol doesn't distinguish between message calls to External Owned Accounts (personal accounts) from message calls to Contract Accounts, so we should be able to send data in any message call. And if my understanding is correct, then this behaviour from Ganache should be considered as an incompatibility bug.

**Comment by guipozo** [comment] 2018-07-05 11:49
I'm trying to send a transaction with some data to an account (not a contract) and i'm receiving:

`Attempting to run transaction which calls a contract function, but recipient address 0x6e2e3accbe4b1320107118147a7cb6f5b689ea2f is not a contract address`.

Ethereum "blocks/disable" transactions (Acc2Acc) with data? It's normal?

**Comment by davidmurdoch** [comment] 2018-08-14 17:38
Another case where this contract check becomes a problem is if the specified `blockNumber` is propagated through to `createFakeTransactionWithCorrectNonce` like in https://github.com/area/ganache-core/commit/6848a954576d8017cc85d52c172a26d583eb1f18

At first glance this commit looks like it should be correct. Unfortunately, some tests fail when we are doing an `eth_call` to a contract on a specific block at a point when this contract doesn't/didn't exist (like on the `"earliest:"` block). Specifically: https://github.com/trufflesuite/ganache-core/blob/4d157067dcc9445313af8dd719f609452e2ba63c/test/requests.js#L762

**Comment by emurmotol** [comment] 2018-08-22 02:55
Any news about this? I'm also having this issue [#878](https://github.com/trufflesuite/ganache/issues/878)

**Comment by davidmurdoch** [comment] 2018-08-22 17:46
@emurmotol Not yet. It's on our high-priority list! We'll be sure to update this issue when the fix is in.

**Comment by benjamincburns** [comment] 2018-08-28 02:02
@bordalix et al:

@adibas03 kindly submitted a PR to correct this issue, however in the process of validating that such a change reflects the rest of the ethereum ecosystem I've failed to surface how it would be possible to make use of arbitrary data tacked onto a transaction sent to a simple (non-contract) account.

I can't see anything in the Yellow Paper so far which strictly _prohibits_ adding in message call data to a transaction to a simple address, but I also can't see a mechanism which makes this a useful activity. That is, I can't find anything which allows you to read this data back out. That is, `eth_getTransactionByHash` and similar don't return the `data` field of the transaction input, and neither does `eth_getTransactionReceipt`.

Assuming I'm not missing something and there really is no direct way to read it back out from the RPC layer or from within a contract, I'd rather we continued to warn users off from it.

**Comment by benjamincburns** [comment] 2018-08-28 02:06
Just my luck! As soon as I wrote that comment @davidmurdoch & @seesemichaelj pointed out to me that the field I was looking for on the RPC response was `input`. I've accepted @adibas03's PR, and as a result I'm closing this issue.

**Closed by benjamincburns** 2018-08-28 02:06 UTC
Labels: bug, help wanted, priority-high

**Comment by timohe** [comment] 2018-11-01 14:48
I am still having this issue using https://hub.docker.com/r/trufflesuite/ganache-cli/ or the mac application. Is this just not updated yet?

**Comment by fforbeck** [comment] 2018-11-02 15:55
I am getting the same issue with ganache-core: 2.2.1. I saw the fix (#159) was merged on 27 Aug but last release was 16 Aug. Is there an ETA for the new release?

**Comment by davidmurdoch** [comment] 2018-11-04 19:00
@timohe, @fforbeck We hope to push a release out this week and get into a regular release cadence from here on out.

**Comment by fforbeck** [comment] 2018-11-05 16:09
Cool! Thanks @davidmurdoch

**Comment by timohe** [comment] 2018-11-24 16:02
Worked for me with the new docker release

**Comment by davidmurdoch** [comment] 2018-11-24 16:38
@jordybaylac, what version of ganache-core?

**Comment by JordyBaylac** [comment] 2018-11-24 18:54
Hi @davidmurdoch, not ganache-core, but in the Mac Installer version.

**Comment by davidmurdoch** [comment] 2018-11-24 19:07
@jordybaylac, I haven't yet released a new Ganache UI with the fixes in ganache-core. There were some regressions in the 6.2.0 release that I've been working on that have kept me from releasing a UI update, but I hope to have these all resolved early this week so I can get a new UI release out.

If you can't wait or just want to try it out you can build directly from the `develop` branch of https://github.com/trufflesuite/ganache, just install npm then run `npm install` then `npm start` and it should start up after a minute or so (you'll also need to have a python 2.7 executable on your path otherwise the install will fail). Feel free to report any issues/bugs you may find!
