### ISSUE TITLE
block.coinbase does only return 0x

### ISSUE THREAD

**Issue by loki-sama** [trufflesuite/ganache-core#201] opened 2018-10-20 13:56 UTC
## Expected Behavior
I expected to get accounts[0] as `block.coinbase`.

## Current Behavior
I got 0x0000000000000000000000000000000000000000 as `block.coinbase`.

`curl -X POST --data '{"jsonrpc":"2.0", "method":"eth_coinbase", "params":[],"id":9999}' 127.0.0.1:8545`
Gives me accounts[0].

## Steps to Reproduce (for bugs)

1. run ganache-cli
2. deploy contract
```
pragma solidity ^0.4.24;


contract TestCoinbase {

    function getCoinbase() public returns (address){
        return block.coinbase;
    }
}
```
3. call getCoinbase

## Context
Try to run tests for code that uses block.coinbase.

## Your Environment
Ganache CLI v6.1.8 (ganache-core: 2.2.1)
OSX 10.13.6

**Comment by davidmurdoch** [comment] 2018-10-20 14:45
Thanks for reporting this @loki-sama. I've confirmed that this is still an issue on our `develop` branch and have filed this bug to our issue backlog.

**Comment by Goldenflamer** [comment] 2020-01-29 09:44
This is still an issue in 2020

**Comment by nicholasjpaterno** [comment] 2020-01-29 17:49
@Goldenflamer Thanks for the bump on this issue.  Unfortunately this is a little lower priority than some of our other issues.  That said, I plan on fixing this ASAP but if this is a blocker for you we highly encourage PR's!

**Comment by davidmurdoch** [comment] 2020-10-06 21:27
`block.coinbase` is actually intended to be the `0x0` address, as it is the block that receives the reward. The bug is that `eth_coinbase` returns `accounts[0]`.

The reason the block coinbase can't be accounts[0] by default is that each block would change the accounts balance, and would then break many tests that rely on this behavior.

This will be fixed in the next major version of ganache, where we'll allow for configuring the coinbase address.

**Comment by davidmurdoch** [comment] 2020-12-07 20:16
done in ganache@3.0.0-internal.0

**Closed by davidmurdoch** 2020-12-07 20:16 UTC
Labels: bug, correctness/consistency, priority-medium
