### ISSUE TITLE
Using Ganache Core as a provider causes test to hang forever

### ISSUE THREAD

**Issue by kdelwat** [trufflesuite/ganache-core#266] opened 2018-12-27 00:21 UTC
I'm trying to run tests using Jest and Typescript, using Ganache as a Web3 provider to act as a simulated blockchain to test against. However, any call to `Ganache.provider()` causes the test to hang and never complete with no feedback. Any help would be very appreciated 😄 

## Expected Behavior
- Ganache can be added to web3 as a provider without issue for use in tests

## Current Behavior
- If the test includes any call to `ganache.provider()`, as detailed in the README, the test will hang and never complete. This does not depend on web3 or any other library.

## Steps to Reproduce (for bugs)

See the minimal example at: https://github.com/kdelwat/Ganache-Core-test-example

In `ganache.test.ts` is a test which currently will not complete. Commenting out the `Ganache.provider()` line will allow the test to complete.

Run `npm run test` to run jest
1. `git clone https://github.com/kdelwat/Ganache-Core-test-example`
2. `cd https://github.com/kdelwat/Ganache-Core-test-example`
3. `npm install`
4. `npm run test`

## Context

I'm trying to write integration tests for a server which uses both databases and smart contracts as backends; the idea is to use ganache to mock the contract backend for these integration tests, so that they can be run in continuous integration.

## Your Environment
* Version used: 6.2.5
* Node: v9.11.1
* Operating System and version: Windows 10, Windows Subsystem for Linux with Ubuntu 16.04.5 LTS

**Comment by nicholasjpaterno** [comment] 2019-01-02 20:51
@kdelwat Thanks for taking the time to post this issue.  I had a chance to talk this over with @cds-amal and it appears the issue is in the `tsconfig.json` file.

@cds-amal has submitted a PR documenting the changes here: https://github.com/kdelwat/Ganache-Core-test-example/pull/1

I'm going to close this for now.  Please feel free to reopen if these issues resurface!

**Closed by nicholasjpaterno** 2019-01-02 20:51 UTC

**Comment by jtakalai** [comment] 2022-07-26 09:35
EDIT: clarification: NOT hanging, but still segfaulting and exiting with 1...

I'm getting segfaults in Github CI (on my machine it works fine)

Here's excerpts from [the CI run log](https://github.com/dataunions/data-unions/runs/7517212165?check_suite_focus=true):

[Line 515](https://github.com/dataunions/data-unions/runs/7517212165?check_suite_focus=true#step:7:515)
```
> @dataunions/client@3.0.0-beta.1 unit-test
> jest --runInBand test/unit

(node:2261) V8: /home/runner/work/data-unions/data-unions/node_modules/ganache/dist/node/0.js:2 Linking failure in asm.js: Unexpected stdlib member
(Use `node --trace-warnings ...` to show where the warning was created)
PASS test/unit/withdraw.test.ts (25.143 s)
```

and in the very end:
```
Test Suites: 7 passed, 7 total
Tests:       2 skipped, 23 passed, 25 total
Snapshots:   0 total
Time:        74.059 s
Ran all test suites matching /test\/unit/i.
Segmentation fault (core dumped)
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @dataunions/client@3.0.0-beta.1 
npm ERR!   at location: /home/runner/work/data-unions/data-unions/packages/client 
Error: Process completed with exit code 1.
```

My own machine: Mac OS 12.2.1, node 16.13.2
Github CI machine: ubuntu-20.04, node 16.13.2
