### ISSUE TITLE
Can't get multiple transactions in one block when using -b

### ISSUE THREAD

**Issue by jpmonettas** [trufflesuite/ganache-core#528] opened 2020-01-08 12:06 UTC
Running ganache-cli(6.1.8) with -b 5 and submitting 4 transactions in a row should result in the 4 transactions being mined in the same block. Instead I'm seeing each transaction being mined in a separate block.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [X]
* Link to my question on gitter: [January 7, 2020 1:37 PM](https://gitter.im/ConsenSys/truffle?at=5e14b3ac04adee486b49491e)

> hello everybody!
> I'm running ganache-cli (6.1.8) with -b 5 and doing a bunch of eth_sendTransaction together. I see in ganache console that the transactions are being sent one after the other very quickly but I'm also seeing ganache processing each of them when mining a different block, so all transactions end up in different blocks which is not what I'm trying to accomplish.
> Any ideas?

## Expected Behavior

Each transaction should be mined in the same block when ganache-cli runs with -b t and the sum of all times between transaction submission is < t.

## Current Behavior

Each transaction is mined in a separate block.

## Steps to Reproduce (for bugs)

1. Run ganache-cli like :
```
ganache-cli -b 5 -v | grep et"eth_sendTransaction\|Transaction\|Block Number"
```

so you can see transaction submissions and transactions being mined with block number.

2. Submit 4 transactions in a row using web3js 
3. Check in ganache log that all transactions were sent one after the other  but it mines one block per transaction. It mines one block every 5 seconds (this is expected) but it includes 1 tx per block. 

## Your Environment
* Version used: 6.1.8
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: v11.14.0
* Operating System and version (include distro if Linux): Debian Linux

**Comment by jpmonettas** [comment] 2020-01-14 20:06
@nicholasjpaterno great thanks!! 
Yeah I'm already unblocked, just giving it less gas to each tx so they don't exceed the limit makes the trick.

**Comment by gnidan** [comment] 2021-03-24 17:39
So to summarize, it sounds like the issue is that Ganache allocates blocks based on the provided gas _limit_, not the actual gas used. Hence why this is a bug.

This should be fixed in the upcoming v7.0.0, since that major version will redo how Ganache allocates block space.

Thanks all!

**Comment by davidmurdoch** [comment] 2021-08-06 17:22
Confirmed that this will be fixed in ganache v7! You can try it now by installing our canary version: `npm uninstall ganache-cli -g && npm install ganache@canary -g`

**Closed by davidmurdoch** 2021-08-06 17:22 UTC
Labels: bug, priority4 📋, correctness/consistency

**Comment by Spider149** [comment] 2022-05-04 11:47
> Confirmed that this will be fixed in ganache v7! You can try it now by installing our canary version: `npm uninstall ganache-cli -g && npm install ganache@canary -g`

I'm using: 
ganache@7.1.0
truffle version:
Truffle v5.5.11 (core: 5.5.11)
Ganache v^7.0.4
Solidity - 0.8.13 (solc-js)
Node v16.14.2
Web3.js v1.5.3

ganache -b 5 -l 100000000
and then truffle test /test/mytest.js
When i make a transaction, new block is still mined although gas limit of each transaction is much smaller than block gas limit
