### ISSUE TITLE
Ganache core returns inconsistent chain ids

### ISSUE THREAD

**Issue by yahgwai** [trufflesuite/ganache-core#575] opened 2020-05-18 16:27 UTC
The chainid is different when queried via different methods.
* Chainid retrieved via the chainid opcode in a contract
* Chainid retrieved via the getNetwork().chainId on an ethers provider (this could be ethers fault I guess)
* Chainid retrived via the `eth_chainid` rpc call

## Expected Behavior
All the chain ids should be the same

## Current Behavior
The chain ids are different

## Steps to Reproduce (for bugs)
The following contract:
```
pragma solidity 0.6.2;

contract ChainIdChecker {
    function getChainID() public pure returns(uint) {
        // Fetch chainId
        uint256 chainId;
        assembly {chainId := chainid() }
        return chainId;
    }
}
```
executed against with the following code

```
const ganache = Ganache.provider();

const ethers.providers.web3Provider = new Web3Provider(ganache as AsyncSendable);
const admin = await web3Provider.getSigner(0);
const chainIdChecker = await new ChainIdCheckerFactory(admin).deploy();
        
console.log((await chainIdChecker.getChainID()).toString());
console.log((await web3Provider.getNetwork()).chainId.toString());
console.log(new BigNumber(await web3Provider.send("eth_chainId", [])).toNumber())
```
gives the following output:
```
1
1589819236228
1337
```

## Context
I need to verify a chain id on chain, from data supplied in a transaction

## Your Environment
* Version used: Ganache 2.10.2
* Operating System and version: Ubuntu 20.04

**Comment by davidmurdoch** [comment] 2020-05-18 16:44
Thanks for opening this issue. This is a know problem that we are working on fixing in the next major release.

As a temporary stop-gap we added an undocumented "private" option, `_chainId` (the option will be renamed `chainId` in the next major release). Set the options `_chainId` and `network_id` to `1337` when initializing a ganache-core provider or server to align these values. Unfortunately, `1337` is the only value that will currently work around this bug.

Example:

```javascript
const provider = Ganache.provider({
	_chainId: 1337,
	network_id: 1337
});
```

Let me know if this works for you.

_note: a network's chain id and network id are not supposed to be comparable/interchangeable; they both serve different purposes_

**Comment by yahgwai** [comment] 2020-05-18 16:55
Yep, thanks, that works. I'm building a client library that people can inject a provider into, so unfortunately i don't have control over what they set the chain id. But I can pass on the work-around for now.

**Comment by LADYBEAR7819** [comment] 2020-05-19 06:50
``

> Yep, thanks, that works. I'm building a client library that people can inject a provider into, so unfortunately i don't have control over what they set the chain id. But I can pass on the work-around for now.

**Comment by LADYBEAR7819** [comment] 2020-05-19 06:52
> ``
> 
> > Yep, thanks, that works. I'm building a client library that people can inject a provider into, so unfortunately i don't have control over what they set the chain id. But I can pass on the work-around for now.

[https://github.com/trufflesuite/ganache-core/issues/575#issuecomment-630310929]()

**Comment by dmihal** [comment] 2020-09-11 11:08
I believe this is a duplicate of #515

**Comment by davidmurdoch** [comment] 2020-09-11 18:11
Thanks @dmihal I'll close this one and continue tracking it in https://github.com/trufflesuite/ganache-core/issues/515

**Closed by davidmurdoch** 2020-09-11 18:11 UTC
